# Generated by Django 5.1.4 on 2024-12-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stars', models.DecimalField(decimal_places=2, max_digits=3)),
                ('link', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('category_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'listing_product',
            },
        ),
    ]
